import type { Metadata } from "next";
import "./globals.css";
import { Outfit } from "next/font/google";
import Nav from "@/components/UI/Nav";

const outfit = Outfit({subsets: ['latin']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import {
  ClerkProvider,
  SignedIn,
  SignedOut,
} from '@clerk/nextjs'
import Footer from "@/components/UI/Footer";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider dynamic>
      <html lang="en" className="!scroll-smooth">
        <body className={outfit.className}>
          <Nav />
          <SignedOut>
          </SignedOut>
          <SignedIn>
            {children}
          </SignedIn>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  )
}
